### ISSUE TITLE
Traffic sign requests

### ISSUE THREAD

**Issue by knikel** [mapillary/mapillary_sprite_source#6]
Traffic signs below have been requested in [mapillary/traffico](https://github.com/mapillary/traffico). 

> **NOTE**: Adding a new sign doesn't mean we'll start detecting it, since we have to enable that functionality in the backend

- [ ] `speed-/traffic camera (EU, US, UK)`, see https://github.com/mapillary/traffico/issues/45
- [ ] `Generic bike route (US)`, see https://github.com/mapillary/traffico/issues/40
- [ ] `Living zone on/off (US, EU)`, see https://github.com/mapillary/traffico/issues/36
